#!/bin/bash

# Prerequisits
bash var.sh
source var.sh
source ask.sh

# to automount network location (eq samba server) look at this example and replicate:


# Automount Data Partition
cat /etc/fstab

if ask "Do you want to automount the NTFS Data Partition now?"; then
	# Copy backup of fstab
	cp  /etc/fstab fstab_backup/fstab_"$(date +%Y%m%d_%H%M%S)"
	echo "fstab copied to 'Home'"
	echo
	sudo mkdir "$data_dir"
	# display all partitions and relevant info to figure it out
	sudo fdisk -l
	read -p "enter partition ('sda1')" data_LABEL

	# Make uuid a variable
	data_uuid=$(blkid -d -o value -s UUID /dev/"$data_LABEL")

	# last Step: actually edit /etc/fstab
	ls -l /dev/disk/by-uuid

	echo 
	echo "$data_LABEL $data_uuid"
	
	if ask "Is this the correct UUID of the Data partition?"; then
		{
		sudo echo "#"
		sudo echo "# the following is generated by automount_partitions.sh"
		sudo echo "#"
		# The most interesting Command in this hole script
		sudo echo "UUID=$data_uuid $data_dir ntfs umask=000,utf8 0 0" 
		} >> /etc/fstab
				
		echo		
		echo "this is the new /etc/fstab"
		cat /etc/fstab
		echo
		
		if ask "correct? "; then
			echo "$data_dir successfully mounted"
		fi
		# Create symlinks to Home Directory
		bash symlink_homedir.sh
	fi
fi

# Automount Windows(OS) Partition
cat /etc/fstab

if ask "Do you want to automount the NTFS Windows(OS) Partition now?"; then
	# Copy backup of fstab
	cp  /etc/fstab fstab_backup/fstab_"$(date +%Y%m%d_%H%M%S)"
	echo "fstab copied to 'Home'"
	echo
	sudo mkdir "$win_dir"
	# display all partitions and relevant info to figure it out
	sudo fdisk -l
	read -p "enter partition ('sda1')" windows_LABEL

	# Make uuid a variable
	win_uuid=$(blkid -d -o value -s UUID /dev/"$windows_LABEL")
	
	ls -l /dev/disk/by-uuid
	echo 
	echo "$windows_LABEL $win_uuid"
	
	if ask "Is this the correct UUID of the Windows partition?"; then
		{
		sudo echo "#"
		# The most interesting Command in this hole script
		sudo echo "UUID=$win_uuid $win_dir ntfs umask=000,utf8 0 0"
		} >> /etc/fstab		
		echo		
		echo "this is the new /etc/fstab"
		cat /etc/fstab
		echo
		
		if ask "correct? "; then
			echo "$win_dir successfully mounted"
		fi
	fi
	echo "automount Complete"
fi
sudo umount -a
sudo mount -a
